FROM node:22-alpine3.21

WORKDIR /usr/src/app


COPY backend/package*.json ./
COPY backend/tsconfig.json ./
RUN npm install

COPY backend/ ./
RUN npx prisma generate

RUN npm run build

EXPOSE 4000

CMD [ "node", "dist/server.js" ]