FROM node:22-alpine3.21

WORKDIR /usr/src/app


COPY backend/package*.json ./
COPY backend/tsconfig.json ./
RUN npm install

COPY backend/ ./

# this is needed so that the database url is set in the container during build time
# ARG DATABASE_URL
# ENV DATABASE_URL=$DATABASE_URL

# ARG JWT_SECRET
# ENV JWT_SECRET=$JWT_SECRET

RUN npx prisma generate

RUN npm run build

EXPOSE 4000

CMD [ "node", "dist/server.js" ]